# Generated by Django 3.0.2 on 2020-01-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deals',
            new_name='Deal',
        ),
    ]
