# Generated by Django 3.0.2 on 2020-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200124_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='publish',
            field=models.DateField(auto_now_add=True),
        ),
    ]
